### PR TITLE
[NO MERGE] server: verify dispatcher exists before using

### PR DESCRIPTION
**Pull request by aalness**

### CODE REVIEW

**Comment by maxtaco** [comment]
Andy this stuff is very much in flux.  Ask @akalin-keybase for the latest?

**Comment by akalin-keybase** [comment]
Yeah, wait a bit -- I'll be moving everything to use keybase/go-framed-msgpack-rpc instead of this. Perhaps redo this pull request on top of that?

**Comment by aalness** [comment]
rgr

**Comment by aalness** [comment]
Ah, this is already fixed in the keybase fork. Closing.

**Comment by akalin-keybase** [comment]
Cool, https://github.com/keybase/kbfs/pull/441 will fix this then.

**Pull request closed without merging**
